### ISSUE TITLE
Station install is broken

### ISSUE THREAD

**Issue by tomaszmrugalski** [gut-space/svarog#67]
I've encountered multiple problems when installing svarog on a new raspberry image:

1. After installing meteor demod, it installed itself in `/usr/local/bin/` as `meteor_demod`, but our install script looks for `meteor-demod`. Had to do `sudo mv meteor_demod meteor-demod`.
2. Following the installation guide, I did `python setup.py install`, which errored out with the following error:
```
error: can't create or remove files in install directory

The following error occurred while trying to add or remove files in the
installation directory:

    [Errno 13] Permission denied: '/usr/local/lib/python3.9/dist-packages/test-easy-install-11195.write-test'
```

When trying to run with sudo, it then complained about missing noaa-apt and medet that were installed in the pi's user directory.
3. The numpy version in requirements.txt is broken. I've skipped the setup.py and did `pip install -r requirements.txt`. Then ran the cli.py script and got the following error:

```
$ station
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
Traceback (most recent call last):
  File "/home/pi/devel/svarog/station/cli.py", line 24, in <module>
    from recipes.factory import get_recipe_names
  File "/home/pi/devel/svarog/station/recipes/__init__.py", line 3, in <module>
    import recipes.noaa_apt_gr
  File "/home/pi/devel/svarog/station/recipes/noaa_apt_gr.py", line 8, in <module>
    import waterfall
  File "/home/pi/devel/svarog/station/waterfall.py", line 3, in <module>
    import matplotlib
  File "/home/pi/.local/lib/python3.9/site-packages/matplotlib/__init__.py", line 205, in <module>
    _check_versions()
  File "/home/pi/.local/lib/python3.9/site-packages/matplotlib/__init__.py", line 190, in _check_versions
    from . import ft2font
ImportError: numpy.core.multiarray failed to import
```

This can be fixed with `pip install --upgrade numpy` (to be run as pi, not as root). There is python3-numpy 1.19.5 install from raspbian (that can't be uninstalled, because gnuradio packages depend on it). When running pip as pi user, the packages are installed in `/home/pi/.local/lib/python3.9/site-packages`.

**Comment by tomaszmrugalski** [comment]
The incorrect numpy version was fixed with commit 06457874801123ec804dfe65c924f3d60db8940c.
