### ISSUE TITLE
Console charts are broken

### ISSUE THREAD

**Issue by tomaszmrugalski** [gut-space/svarog#81]
Attempting to view the next pass causes the code to throw.

```
pi@raspberrypi:~ $ station pass "NOAA 15"
Satellite: NOAA 15
AOS: 2022-02-19 15:05:34.797740+00:00
LOS: 2022-02-19 15:17:40.558562+00:00
Duration: 0:12:05.760822
Max elevation: 13.68 deg 2022-02-19 15:11:36.170338+00:00
Off nadir 59.48 deg
Traceback (most recent call last):
  File "/home/pi/devel/svarog/station/cli.py", line 296, in <module>
    az_elev_chart.plot(sat_name, pass_.aos, pass_.los, location,
  File "/home/pi/devel/svarog/station/az_elev_chart.py", line 129, in plot
    _plot_polar_azimuth_elevation(azimuth_series, elevation_series,
  File "/home/pi/devel/svarog/station/az_elev_chart.py", line 210, in _plot_polar_azimuth_elevation
    print(canvas.plot())
  File "/home/pi/.local/lib/python3.9/site-packages/plotille/_canvas.py", line 376, in plot
    return linesep.join(''.join(map(six.text_type, row))
  File "/home/pi/.local/lib/python3.9/site-packages/plotille/_canvas.py", line 376, in <genexpr>
    return linesep.join(''.join(map(six.text_type, row))
  File "/home/pi/.local/lib/python3.9/site-packages/plotille/_dots.py", line 118, in __str__
    return color(res, fg=self.fg, bg=self.bg, **self.color_kwargs)
TypeError: color() got an unexpected keyword argument 'color_mode'
```

This is on TKIS-1, but also on my dev box. For the reference, here's the list of package:

```
$ pip list
Package                Version   Editable project location
---------------------- --------- --------------------------------------------------------
analog-noise-estimator 1.0.0     /home/pi/devel/svarog/station/src/analog-noise-estimator
arandr                 0.1.10
astroid                2.5.1
asttokens              2.0.4
automationhat          0.2.0
beautifulsoup4         4.9.3
blinker                1.4
blinkt                 0.1.2
buttonshim             0.0.2
Cap1xxx                0.1.3
certifi                2021.10.8
chardet                4.0.0
charset-normalizer     2.0.9
click                  7.1.2
colorama               0.4.4
colorzero              1.1
cron-descriptor        1.2.24
croniter               1.1.0
cryptography           3.3.2
cupshelpers            1.0
cycler                 0.11.0
DateTimeRange          1.2.0
dbus-python            1.2.16
deepdiff               5.7.0
distro                 1.5.0
docutils               0.16
drumhat                0.1.0
envirophat             1.0.0
ExplorerHAT            0.4.2
Flask                  1.1.2
fonttools              4.28.5
fourletterphat         0.1.0
gpiozero               1.6.2
html5lib               1.1
idna                   3.3
isort                  5.6.4
itsdangerous           1.1.0
jedi                   0.18.0
Jinja2                 2.11.3
kiwisolver             1.3.2
lazy-object-proxy      0.0.0
logilab-common         1.8.1
lxml                   4.6.3
MarkupSafe             1.1.1
matplotlib             3.5.1
mbstrdecoder           1.1.0
mccabe                 0.6.1
microdotphat           0.2.1
mote                   0.0.4
motephat               0.0.3
mypy                   0.812
mypy-extensions        0.4.3
numpy                  1.21.5
oauthlib               3.1.0
olefile                0.46
orbit-predictor        1.14.2
ordered-set            4.0.2
packaging              21.3
pantilthat             0.0.7
parso                  0.8.1
pexpect                4.8.0
pgzero                 1.2
phatbeat               0.1.1
pianohat               0.1.0
picamera               1.13
piglow                 1.2.5
pigpio                 1.78
Pillow                 8.4.0
pip                    21.3.1
plotille               4.0.1
psutil                 5.8.0
pycairo                1.16.2
pycups                 2.0.1
pygame                 1.9.6
Pygments               2.7.1
PyGObject              3.38.0
pyinotify              0.9.6
PyJWT                  1.7.1
pylint                 2.7.2
pyOpenSSL              20.0.1
pyparsing              3.0.6
pyserial               3.5b0
pysmbc                 1.0.23
python-apt             2.2.1
python-crontab         2.6.0
python-dateutil        2.8.2
pytz                   2021.3
PyYAML                 6.0
rainbowhat             0.1.0
reportlab              3.5.59
requests               2.26.0
requests-oauthlib      1.0.0
responses              0.12.1
roman                  2.0.0
RPi.GPIO               0.7.0
RTIMULib               7.2.1
scrollphat             0.0.7
scrollphathd           1.2.1
Send2Trash             1.6.0b1
sense-hat              2.2.0
setuptools             52.0.0
sgp4                   2.20
sh                     1.14.2
simplejson             3.17.2
six                    1.16.0
skywriter              0.0.7
sn3218                 1.2.7
soupsieve              2.2.1
spidev                 3.5
ssh-import-id          5.10
thonny                 3.3.14
toml                   0.10.1
touchphat              0.0.1
twython                3.8.2
typed-ast              1.4.2
typepy                 1.3.0
typing_extensions      4.0.1
unicornhathd           0.0.4
urllib3                1.26.7
webencodings           0.5.1
Werkzeug               1.0.1
wheel                  0.34.2
wrapt                  1.12.1
```

**Comment by tomaszmrugalski** [comment]
The problem has been fixed in #82.
